---
output: github_document
---


```{r include=FALSE}
knitr::opts_chunk$set(
  echo=FALSE,
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
# Please put your title here to include it in the file below.
Title <- "Multi-species occupancy models: an effective and flexible framework for studies of insect communities"
```

# MSOM for insect communities

This repository contains the data and code for our paper:

> Mourguiart, B., Couturier, T., Braud, Y., Mansons, J., Combrisson, D. and Besnard, A. (2021), _`r Title`_. Ecological Entomology, 46: 163-174. <https://doi.org/10.1111/een.12991>. 

<<<<<<< HEAD
Scripts in the folder [Analysis](Analyse) allow formatting the data ([creation_data.R](https://github.com/bmourgui/msom_orthoptera/blob/main/Analyse/creation_data.R)) and running the multi-species occupancy model ([Model_paper_published.R](https://github.com/bmourgui/msom_orthoptera/blob/main/Analyse/Model_paper_published.R)) presented in the article. [Redaction/Rmd_Paper_MSOM.Rmd](https://github.com/bmourgui/msom_orthoptera/blob/main/Redaction/Rmd_Paper_MSOM.Rmd) produces the entire manuscript.
=======
Scripts in the folder [Analysis](Analyse) allow formatting the data ([creation_data.R](blob/main/Analyse/creation_data.R)) and running the multi-species occupancy model ([Model_paper_published.R](blob/main/Analyse/Model_paper_published.R)) presented in the article. [Redaction/Rmd_Paper_MSOM.Rmd](blob/main/Redaction/Rmd_Paper_MSOM.Rmd) produces the entire manuscript.
>>>>>>> 7c1ff231035d6f4a4f82f7742cffeca90ac62f99

